name = "dns-over-discord"
type = "javascript"
account_id = "47c2b4d598af9d423c06fc9f936226d5"
workers_dev = true
compatibility_date = "2021-10-17"
kv_namespaces = [
    { binding = "CACHE", id = "fd0fa495945f4fb1bbeb22324b30445c", preview_id = "fd0fa495945f4fb1bbeb22324b30445c" }
]

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[env.staging]
zone_id = "63feb9b9ee057b117f7c833928b0d21f"
workers_dev = false
route = "dns-over-discord-staging.v4.wtf/*"
kv_namespaces = [
    { binding = "CACHE", id = "fd0fa495945f4fb1bbeb22324b30445c" }
]

[env.production]
zone_id = "63feb9b9ee057b117f7c833928b0d21f"
workers_dev = false
route = "dns-over-discord.v4.wtf/*"
kv_namespaces = [
    { binding = "CACHE", id = "fd0fa495945f4fb1bbeb22324b30445c" }
]

